image:
  file: .gitpod.dockerfile

github:
  prebuilds:
    # enable for the master/default branch (defaults to true)
    master: true
    # enable for all branches in this repo (defaults to false)
    branches: false
    # enable for pull requests coming from this repo (defaults to true)
    pullRequests: true
    # enable for pull requests coming from forks (defaults to false)
    pullRequestsFromForks: false
    # add a check to pull requests (defaults to true)
    addCheck: true
    # add a "Review in Gitpod" button as a comment to pull requests (defaults to false)
    addComment: false
    # add a "Review in Gitpod" button to the pull request's description (defaults to false)
    addBadge: false
    # add a label once the prebuild is ready to pull requests (defaults to false)
    addLabel: false

tasks:
  - before: >
      source ~/.bashrc
    init: |
      echo "Wait for the installation"
      yes | sdk i java 8.0.232-open
      sdk i kotlin
      sdkmanager --update
      yes | sdkmanager --licenses
      flutter pub get
      flutter run -d web-server --no-resident
  - command: >
      cd ./todolist &&
      flutter run -d web-server --web-port=8080 --web-hostname=0.0.0.0

ports:
  - port: 8080
    onOpen: open-preview
  - port: 5037
    onOpen: ignore

vscode:
  extensions:
    - Dart-Code.dart-code
    - Dart-Code.flutter
    - Nash.awesome-flutter-snippets
    - adelphes.android-dev-ext
    - fwcd.kotlin
